import unicodedata


SENTENCE_COMPLETION_SEED_DATA = {
    "number": [
        ("I have ___ apple. (jedno)", "one", "jeden"),
        ("She has ___ cats at home. (dve)", "two", "dva"),
        ("I see ___ dogs in the park. (tri)", "three", "tri"),
        ("He has ___ pens on the table. (pat)", "five", "pat"),
        ("I have ___ books to read. (desat)", "ten", "desat"),
        ("There are ___ chairs in the room. (dvadsat)", "twenty", "dvadsat"),
        ("I see ___ birds on the tree. (tridsat)", "thirty", "tridsat"),
        ("She has ___ balls in the garden. (patdesiat)", "fifty", "patdesiat"),
        ("I have ___ toys for my friends. (sto)", "one hundred", "sto"),
        ("He has ___ apples in the basket. (dvesto)", "two hundred", "dvesto"),
        ("I see ___ cars on the street. (patsto)", "five hundred", "patsto"),
        ("She has ___ pencils for school. (tisic)", "one thousand", "tisic"),
        ("I bought ___ oranges yesterday. (sest)", "six", "sest"),
        ("They have ___ chairs in the hall. (osem)", "eight", "osem"),
        ("I saw ___ flowers in the garden. (devat)", "nine", "devat"),
        ("He drank ___ glasses of water. (sedem)", "seven", "sedem"),
        ("I found ___ coins on the floor. (dvadsatpat)", "twenty-five", "dvadsatpat"),
        ("She has ___ hats in her shop. (tridsatpat)", "thirty-five", "tridsatpat"),
        ("I saw ___ cats on the street. (sestdesiat)", "sixty", "sestdesiat"),
        ("He bought ___ books yesterday. (osemdesiat)", "eighty", "osemdesiat"),
        ("I have ___ chairs in my room. (sto pat)", "one hundred five", "sto pat"),
        ("They own ___ bicycles. (dvesto patdesiat)", "two hundred fifty", "dvesto patdesiat"),
        ("I saw ___ stars in the sky. (tristo)", "three hundred", "tristo"),
        ("She found ___ coins in the drawer. (seststo)", "six hundred", "seststo"),
    ],
    "colour": [
        ("The sky is ___. (modra)", "blue", "modra"),
        ("Grass is ___. (zelena)", "green", "zelena"),
        ("The sun is ___. (zlta)", "yellow", "zlta"),
        ("Snow is ___. (biela)", "white", "biela"),
        ("Coal is ___. (cierna)", "black", "cierna"),
        ("My car is ___. (cervena)", "red", "cervena"),
        ("The flower is ___. (oranzova)", "orange", "oranzova"),
        ("Her dress is ___. (ruzova)", "pink", "ruzova"),
        ("The table is ___. (siva)", "gray", "siva"),
        ("My house is ___. (hneda)", "brown", "hneda"),
        ("The ring is ___. (zlata)", "gold", "zlata"),
        ("The bracelet is ___. (strieborna)", "silver", "strieborna"),
        ("The balloon is ___. (fialova)", "purple", "fialova"),
    ],
    "family": [
        ("My ___ is my female parent. (mama)", "mother", "mama"),
        ("I love my ___. (otec)", "father", "otec"),
        ("Her ___ is older than me. (sestra)", "sister", "sestra"),
        ("His ___ plays football. (brat)", "brother", "brat"),
        ("My ___ makes delicious cookies. (babka)", "grandmother", "babka"),
        ("His ___ tells funny stories. (dedko)", "grandfather", "dedko"),
        ("I visited my ___. (teta)", "aunt", "teta"),
        ("We saw our ___. (stryko)", "uncle", "stryko"),
        ("My ___ is very clever. (synovec)", "nephew", "synovec"),
        ("Her ___ likes drawing. (neter)", "niece", "neter"),
        ("My ___ helps me every day. (manzel)", "husband", "manzel"),
        ("Her ___ cooks well. (manzelka)", "wife", "manzelka"),
        ("Their ___ goes to school. (syn)", "son", "syn"),
        ("Our ___ is very kind. (dcera)", "daughter", "dcera"),
        ("I met my ___. (svagrina)", "sister-in-law", "svagrina"),
        ("He talks to his ___. (svagor)", "brother-in-law", "svagor"),
        ("My ___ lives next door. (bratranec / sesternica)", "cousin", "bratranec / sesternica"),
        ("Her ___ loves football. (bratranec)", "cousin", "bratranec"),
        ("I met my ___. (svokra)", "mother-in-law", "svokra"),
        ("His ___ is very friendly. (svokor)", "father-in-law", "svokor"),
        ("They like their ___. (svagor)", "brother-in-law", "svagor"),
        ("We talked to our ___. (svagrina)", "sister-in-law", "svagrina"),
    ],
    "food": [
        ("I drink ___ every morning. (kava)", "coffee", "kava"),
        ("I eat ___ for breakfast. (chlieb)", "bread", "chlieb"),
        ("An ___ a day keeps the doctor away. (jablko)", "apple", "jablko"),
        ("I put ___ on my bread. (maslo)", "butter", "maslo"),
        ("___ is white and comes from cows. (mlieko)", "Milk", "mlieko"),
        ("I like ___ with my salad. (syr)", "cheese", "syr"),
        ("I cook ___ for dinner. (maso)", "meat", "maso"),
        ("We eat ___ on Fridays. (ryba)", "fish", "ryba"),
        ("I eat ___ every day. (zelenina)", "vegetables", "zelenina"),
        ("She likes ___ after lunch. (ovocie)", "fruit", "ovocie"),
        ("I eat a ___ for snack. (banan)", "banana", "banan"),
        ("I love ___ in summer. (jahoda)", "strawberry", "jahoda"),
        ("I cook ___ with meat. (zemiaky)", "potatoes", "zemiaky"),
        ("I eat ___ with curry. (ryza)", "rice", "ryza"),
        ("I eat ___ before dinner. (polievka)", "soup", "polievka"),
        ("I eat ___ with my lunch. (salat)", "salad", "salat"),
        ("I drink ___ in the morning. (caj)", "tea", "caj"),
        ("I drink ___ when I am thirsty. (voda)", "water", "voda"),
        ("I eat a ___ or a pear. (hruska)", "pear", "hruska"),
        ("I peel an ___ before eating. (pomaranc)", "orange", "pomaranc"),
    ],
    "school": [
        ("I write with a ___. (pero)", "pen", "pero"),
        ("I read a ___. (kniha)", "book", "kniha"),
        ("The ___ teaches students. (ucitel)", "teacher", "ucitel"),
        ("I sit on a ___. (stolicka)", "chair", "stolicka"),
        ("I carry my books in a ___. (taska)", "bag", "taska"),
        ("I take notes in a ___. (zosit)", "notebook", "zosit"),
        ("We have a ___ every morning. (hodina)", "lesson", "hodina"),
        ("The ___ is green and big. (tabula)", "blackboard", "tabula"),
        ("I sit at a ___. (stol)", "desk", "stol"),
        ("I am a ___. (ziak/ziacka)", "student", "ziak/ziacka"),
        ("Our ___ shows our subjects. (rozvrh)", "schedule", "rozvrh"),
        ("I do my ___ at home. (domaca uloha)", "homework", "domaca uloha"),
        ("I have a ___ tomorrow. (skuska)", "exam", "skuska"),
        ("We have a short ___ now. (prestavka)", "break", "prestavka"),
        ("I got a good ___ on my test. (znamka)", "grade", "znamka"),
        ("The ___ writes on the blackboard. (ucitel/ucitelka)", "teacher", "ucitel/ucitelka"),
        ("I read my ___ before class. (kniha)", "book", "kniha"),
        ("I write my answers in my ___. (zosit)", "notebook", "zosit"),
        ("I put my pen and pencil in my ___. (taska)", "bag", "taska"),
    ],
    "animal": [
        ("My ___ barks loudly. (pes)", "dog", "pes"),
        ("I walk my __ every morning. (pes)", "dog", "pes"),
        ("The ___ sleeps on the sofa. (macka)", "cat", "macka"),
        ("I feed my ___ milk. (macka)", "cat", "macka"),
        ("The ___ runs fast in the field. (kon)", "horse", "kon"),
        ("I ride a ___ on weekends. (kon)", "horse", "kon"),
        ("We milk the ___ every day. (krava)", "cow", "krava"),
        ("The ___ rolls in the mud. (prasa)", "pig", "prasa"),
        ("The ___ gives us wool. (ovca)", "sheep", "ovca"),
        ("I see a ___ on the hill. (koza)", "goat", "koza"),
        ("The ___ lays eggs every morning. (sliepka)", "chicken", "sliepka"),
        ("The ___ crows at dawn. (kohut)", "rooster", "kohut"),
        ("The ___ swims in the pond. (kacica)", "duck", "kacica"),
        ("The ___ honks loudly. (hus)", "goose", "hus"),
        ("The ___ hops fast. (kralik)", "rabbit", "kralik"),
        ("The ___ likes cheese. (mys)", "mouse", "mys"),
        ("The ___ sings in the morning. (vtak)", "bird", "vtak"),
        ("I see a ___ in the aquarium. (ryba)", "fish", "ryba"),
        ("The ___ slithers on the ground. (had)", "snake", "had"),
        ("The ___ jumps into the water. (zaba)", "frog", "zaba"),
        ("The ___ lives in the forest. (medved)", "bear", "medved"),
        ("The ___ howls at night. (vlk)", "wolf", "vlk"),
        ("The ___ is clever and fast. (liska)", "fox", "liska"),
        ("The ___ runs in the forest. (jelen)", "deer", "jelen"),
        ("The ___ has orange stripes. (tiger)", "tiger", "tiger"),
        ("The ___ climbs trees. (opica)", "monkey", "opica"),
    ],
    "alphabet": [
        ("___ you very much! (Dakujem)", "Thank", "th = jazyk medzi zuby"),
        ("I ___ so. (Myslim)", "think", "th = jazyk medzi zuby"),
        ("The ___ is sailing. (lod)", "ship", "sh = š"),
        ("My ___ number is 123. (telefonne)", "phone", "ph = f"),
        ("I have ___ money. (dost)", "enough", "gh = f"),
        ("Please ___ the door. (zatvorte)", "shut", "sh = š"),
        ("I ___ reading books. (milujem)", "love", "v = zvuk v anglictine"),
        ("The baby is ___ loudly. (place)", "crying", "y = aj/e"),
        ("He ___ the guitar well. (hra)", "plays", "ay = ej"),
        ("I ___ my keys. (stratil)", "lost", "o = kratke o"),
        ("They ___ to school every day. (chodia)", "go", "o = kratke o"),
        ("I need to ___ a letter. (napisat)", "write", "wr = tiche w"),
        ("She ___ her homework quickly. (robi)", "does", "o = kratke o"),
        ("The ___ is very bright. (slnko)", "sun", "u = kratke u"),
        ("I ___ a lot of water. (pijem)", "drink", "i = kratke i"),
        ("He ___ a beautiful song. (spieva)", "sings", "ng = nosovy zvuk"),
        ("We ___ pizza for lunch. (jem)", "eat", "ea = i dlhe"),
        ("The cat ___ on the mat. (sedi)", "sits", "i = kratke i"),
        ("___ you like ice cream? (Mas rad)", "Do", "D = dlhe d"),
        ("I ___ very happy today. (som)", "am", "a = kratke a"),
    ],
}


def _normalize(value):
    if value is None:
        return ""
    normalized = unicodedata.normalize("NFKD", str(value))
    without_accents = "".join(char for char in normalized if not unicodedata.combining(char))
    return " ".join(without_accents.strip().lower().split())


def lookup_seed_sentence(lesson_type, answer, hint):
    normalized_answer = _normalize(answer)
    normalized_hint = _normalize(hint)

    for sentence, expected_answer, expected_hint in SENTENCE_COMPLETION_SEED_DATA.get(lesson_type, []):
        if _normalize(expected_answer) == normalized_answer and _normalize(expected_hint) == normalized_hint:
            return sentence

    return ""