import unicodedata


SENTENCE_COMPLETION_SEED_DATA = {
    "number": [
        ("I have ___ apple. (jedno)", "one", "jeden"),
        ("She has ___ cats at home. (dve)", "two", "dva"),
        ("I see ___ dogs in the park. (tri)", "three", "tri"),
        ("He has ___ pens on the table. (päť)", "five", "päť"),
        ("I have ___ books to read. (desať)", "ten", "desať"),
        ("There are ___ chairs in the room. (dvadsať)", "twenty", "dvadsať"),
        ("I see ___ birds on the tree. (tridsať)", "thirty", "tridsať"),
        ("She has ___ balls in the garden. (päťdesiat)", "fifty", "päťdesiat"),
        ("I have ___ toys for my friends. (sto)", "one hundred", "sto"),
        ("He has ___ apples in the basket. (dvesto)", "two hundred", "dvesto"),
        ("I see ___ cars on the street. (päťsto)", "five hundred", "päťsto"),
        ("She has ___ pencils for school. (tisíc)", "one thousand", "tisíc"),
        ("I bought ___ oranges yesterday. (šesť)", "six", "šesť"),
        ("They have ___ chairs in the hall. (osem)", "eight", "osem"),
        ("I saw ___ flowers in the garden. (deväť)", "nine", "deväť"),
        ("He drank ___ glasses of water. (sedem)", "seven", "sedem"),
        ("I found ___ coins on the floor. (dvadsaťpäť)", "twenty-five", "dvadsaťpäť"),
        ("She has ___ hats in her shop. (tridsaťpäť)", "thirty-five", "tridsaťpäť"),
        ("I saw ___ cats on the street. (šesťdesiat)", "sixty", "šesťdesiat"),
        ("He bought ___ books yesterday. (osemdesiat)", "eighty", "osemdesiat"),
        ("I have ___ chairs in my room. (sto päť)", "one hundred five", "sto päť"),
        ("They own ___ bicycles. (dvesto päťdesiat)", "two hundred fifty", "dvesto päťdesiat"),
        ("I saw ___ stars in the sky. (tristo)", "three hundred", "tristo"),
        ("She found ___ coins in the drawer. (šesťsto)", "six hundred", "šesťsto"),
    ],
    "colour": [
        ("The sky is ___. (modrá)", "blue", "modrá"),
        ("Grass is ___. (zelená)", "green", "zelená"),
        ("The sun is ___. (žltá)", "yellow", "žltá"),
        ("Snow is ___. (biela)", "white", "biela"),
        ("Coal is ___. (čierna)", "black", "čierna"),
        ("My car is ___. (červená)", "red", "červená"),
        ("The flower is ___. (oranžová)", "orange", "oranžová"),
        ("Her dress is ___. (ružová)", "pink", "ružová"),
        ("The table is ___. (sivá)", "gray", "sivá"),
        ("My house is ___. (hnedá)", "brown", "hnedá"),
        ("The ring is ___. (zlatá)", "gold", "zlatá"),
        ("The bracelet is ___. (strieborná)", "silver", "strieborná"),
        ("The balloon is ___. (fialová)", "purple", "fialová"),
    ],
    "family": [
        ("My ___ is my female parent. (mama)", "mother", "mama"),
        ("I love my ___. (otec)", "father", "otec"),
        ("Her ___ is older than me. (sestra)", "sister", "sestra"),
        ("His ___ plays football. (brat)", "brother", "brat"),
        ("My ___ makes delicious cookies. (babka)", "grandmother", "babka"),
        ("His ___ tells funny stories. (dedko)", "grandfather", "dedko"),
        ("I visited my ___. (teta)", "aunt", "teta"),
        ("We saw our ___. (strýko)", "uncle", "strýko"),
        ("My ___ is very clever. (synovec)", "nephew", "synovec"),
        ("Her ___ likes drawing. (neter)", "niece", "neter"),
        ("My ___ helps me every day. (manžel)", "husband", "manžel"),
        ("Her ___ cooks well. (manželka)", "wife", "manželka"),
        ("Their ___ goes to school. (syn)", "son", "syn"),
        ("Our ___ is very kind. (dcéra)", "daughter", "dcéra"),
        ("I met my ___. (švagriná)", "sister-in-law", "švagriná"),
        ("He talks to his ___. (švagor)", "brother-in-law", "švagor"),
        ("My ___ lives next door. (bratranec / sesternica)", "cousin", "bratranec / sesternica"),
        ("Her ___ loves football. (bratranec)", "cousin", "bratranec"),
        ("I met my ___. (svokra)", "mother-in-law", "svokra"),
        ("His ___ is very friendly. (svokor)", "father-in-law", "svokor"),
        ("They like their ___. (švagor)", "brother-in-law", "švagor"),
        ("We talked to our ___. (švagriná)", "sister-in-law", "švagriná"),
    ],
    "food": [
        ("I drink ___ every morning. (káva)", "coffee", "káva"),
        ("I eat ___ for breakfast. (chlieb)", "bread", "chlieb"),
        ("An ___ a day keeps the doctor away. (jablko)", "apple", "jablko"),
        ("I put ___ on my bread. (maslo)", "butter", "maslo"),
        ("___ is white and comes from cows. (mlieko)", "Milk", "mlieko"),
        ("I like ___ with my salad. (syr)", "cheese", "syr"),
        ("I cook ___ for dinner. (mäso)", "meat", "mäso"),
        ("We eat ___ on Fridays. (ryba)", "fish", "ryba"),
        ("I eat ___ every day. (zelenina)", "vegetables", "zelenina"),
        ("She likes ___ after lunch. (ovocie)", "fruit", "ovocie"),
        ("I eat a ___ for snack. (banán)", "banana", "banán"),
        ("I love ___ in summer. (jahoda)", "strawberry", "jahoda"),
        ("I cook ___ with meat. (zemiaky)", "potatoes", "zemiaky"),
        ("I eat ___ with curry. (ryža)", "rice", "ryža"),
        ("I eat ___ before dinner. (polievka)", "soup", "polievka"),
        ("I eat ___ with my lunch. (šalát)", "salad", "šalát"),
        ("I drink ___ in the morning. (čaj)", "tea", "čaj"),
        ("I drink ___ when I am thirsty. (voda)", "water", "voda"),
        ("I eat a ___ or a pear. (hruška)", "pear", "hruška"),
        ("I peel an ___ before eating. (pomaranč)", "orange", "pomaranč"),
    ],
    "school": [
        ("I write with a ___. (pero)", "pen", "pero"),
        ("I read a ___. (kniha)", "book", "kniha"),
        ("The ___ teaches students. (učiteľ)", "teacher", "učiteľ"),
        ("I sit on a ___. (stolička)", "chair", "stolička"),
        ("I carry my books in a ___. (taška)", "bag", "taška"),
        ("I take notes in a ___. (zošit)", "notebook", "zošit"),
        ("We have a ___ every morning. (hodina)", "lesson", "hodina"),
        ("The ___ is green and big. (tabuľa)", "blackboard", "tabuľa"),
        ("I sit at a ___. (stôl)", "desk", "stôl"),
        ("I am a ___. (žiak/žiačka)", "student", "žiak/žiačka"),
        ("Our ___ shows our subjects. (rozvrh)", "schedule", "rozvrh"),
        ("I do my ___ at home. (domáca úloha)", "homework", "domáca úloha"),
        ("I have a ___ tomorrow. (skúška)", "exam", "skúška"),
        ("We have a short ___ now. (prestávka)", "break", "prestávka"),
        ("I got a good ___ on my test. (známka)", "grade", "známka"),
        ("The ___ writes on the blackboard. (učiteľ/učiteľka)", "teacher", "učiteľ/učiteľka"),
        ("I read my ___ before class. (kniha)", "book", "kniha"),
        ("I write my answers in my ___. (zošit)", "notebook", "zošit"),
        ("I put my pen and pencil in my ___. (taška)", "bag", "taška"),
    ],
    "animal": [
        ("My ___ barks loudly. (pes)", "dog", "pes"),
        ("I walk my __ every morning. (pes)", "dog", "pes"),
        ("The ___ sleeps on the sofa. (mačka)", "cat", "mačka"),
        ("I feed my ___ milk. (mačka)", "cat", "mačka"),
        ("The ___ runs fast in the field. (kôň)", "horse", "kôň"),
        ("I ride a ___ on weekends. (kôň)", "horse", "kôň"),
        ("We milk the ___ every day. (krava)", "cow", "krava"),
        ("The ___ rolls in the mud. (prasa)", "pig", "prasa"),
        ("The ___ gives us wool. (ovca)", "sheep", "ovca"),
        ("I see a ___ on the hill. (koza)", "goat", "koza"),
        ("The ___ lays eggs every morning. (sliepka)", "chicken", "sliepka"),
        ("The ___ crows at dawn. (kohút)", "rooster", "kohút"),
        ("The ___ swims in the pond. (kačica)", "duck", "kačica"),
        ("The ___ honks loudly. (hus)", "goose", "hus"),
        ("The ___ hops fast. (králik)", "rabbit", "králik"),
        ("The ___ likes cheese. (myš)", "mouse", "myš"),
        ("The ___ sings in the morning. (vták)", "bird", "vták"),
        ("I see a ___ in the aquarium. (ryba)", "fish", "ryba"),
        ("The ___ slithers on the ground. (had)", "snake", "had"),
        ("The ___ jumps into the water. (žaba)", "frog", "žaba"),
        ("The ___ lives in the forest. (medveď)", "bear", "medveď"),
        ("The ___ howls at night. (vlk)", "wolf", "vlk"),
        ("The ___ is clever and fast. (líška)", "fox", "líška"),
        ("The ___ runs in the forest. (jeleň)", "deer", "jeleň"),
        ("The ___ has orange stripes. (tiger)", "tiger", "tiger"),
        ("The ___ climbs trees. (opica)", "monkey", "opica"),
    ],
    "alphabet": [
        ("___ you very much! (Ďakujem)", "Thank", "th = jazyk medzi zuby"),
        ("I ___ so. (Myslím)", "think", "th = jazyk medzi zuby"),
        ("The ___ is sailing. (loď)", "ship", "sh = š"),
        ("My ___ number is 123. (telefónne)", "phone", "ph = f"),
        ("I have ___ money. (dosť)", "enough", "gh = f"),
        ("Please ___ the door. (zatvorte)", "shut", "sh = š"),
        ("I ___ reading books. (milujem)", "love", "v = zvuk v angličtine"),
        ("The baby is ___ loudly. (pláče)", "crying", "y = aj/e"),
        ("He ___ the guitar well. (hrá)", "plays", "ay = ej"),
        ("I ___ my keys. (stratil)", "lost", "o = krátke o"),
        ("They ___ to school every day. (chodia)", "go", "o = krátke o"),
        ("I need to ___ a letter. (napísať)", "write", "wr = tiché w"),
        ("She ___ her homework quickly. (robí)", "does", "o = krátke o"),
        ("The ___ is very bright. (slnko)", "sun", "u = krátke u"),
        ("I ___ a lot of water. (pijem)", "drink", "i = krátke i"),
        ("He ___ a beautiful song. (spieva)", "sings", "ng = nosový zvuk"),
        ("We ___ pizza for lunch. (jem)", "eat", "ea = i dlhé"),
        ("The cat ___ on the mat. (sedí)", "sits", "i = krátke i"),
        ("___ you like ice cream? (Máš rád)", "Do", "D = dlhé d"),
        ("I ___ very happy today. (som)", "am", "a = krátke a"),
    ],
}


def _normalize(value):
    if value is None:
        return ""
    normalized = unicodedata.normalize("NFKD", str(value))
    without_accents = "".join(char for char in normalized if not unicodedata.combining(char))
    return " ".join(without_accents.strip().lower().split())


def lookup_seed_sentence(lesson_type, answer, hint):
    normalized_answer = _normalize(answer)
    normalized_hint = _normalize(hint)

    for sentence, expected_answer, expected_hint in SENTENCE_COMPLETION_SEED_DATA.get(lesson_type, []):
        if _normalize(expected_answer) == normalized_answer and _normalize(expected_hint) == normalized_hint:
            return sentence

    return ""