# Generated by Django 5.1.1 on 2026-03-01 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', 'cooked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence_completion',
            old_name='english_sentence',
            new_name='correct_answer',
        ),
        migrations.RenameField(
            model_name='sentence_completion',
            old_name='missing_word',
            new_name='sentence',
        ),
        migrations.AddField(
            model_name='sentence_completion',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sentence_completion',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_completions', to='exercises.exercise'),
        ),
        migrations.AlterField(
            model_name='sentence_completion',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
