# Generated by Django 5.1.1 on 2026-03-02 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_rename_english_sentence_sentence_completion_correct_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence_completion',
            old_name='correct_answer',
            new_name='english_sentence',
        ),
        migrations.RenameField(
            model_name='sentence_completion',
            old_name='sentence',
            new_name='missing_word',
        ),
    ]
