# Generated by Django 5.1.1 on 2026-03-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_rename_correct_answer_sentence_completion_english_sentence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence_completion',
            old_name='english_sentence',
            new_name='correct_answer',
        ),
        migrations.RenameField(
            model_name='sentence_completion',
            old_name='missing_word',
            new_name='sentence',
        ),
    ]
