# Generated by Django 5.1.1 on 2026-03-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_rename_english_sentence_sentence_completion_correct_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence_completion',
            name='correct_answer',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.TextField(choices=[('matching', 'Matching'), ('multiple_choice', 'Multiple Choice'), ('sentence_completion', 'Sentence Completion'), ('word_scrambles', 'Word Scramble')]),
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
