# Generated by Django 5.1.1 on 2026-02-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('uppercase', models.CharField(max_length=5)),
                ('lowercase', models.CharField(max_length=5)),
                ('pronunciation', models.FileField(blank=True, null=True, upload_to='letters/')),
                ('category', models.CharField(choices=[('vowel', 'Vowel'), ('consonant', 'Consonant')], max_length=10)),
                ('pronunciation_in_slovak', models.CharField(max_length=10)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
