# Generated by Django 5.1.1 on 2026-02-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphabet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='lowercase',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='letter',
            name='uppercase',
            field=models.CharField(max_length=5),
        ),
    ]
