# Generated by Django 5.1.1 on 2026-02-06 20:08

from django.db import migrations

def load_english_alphabet(apps, schema_editor):
    Letter = apps.get_model('alphabet', 'Letter')

    letters = [
        ('A', 'a', '/eɪ/', 'vowel'),
        ('B', 'b', '/biː/', 'consonant'),
        ('C', 'c', '/siː/', 'consonant'),
        ('D', 'd', '/diː/', 'consonant'),
        ('E', 'e', '/iː/', 'vowel'),
        ('F', 'f', '/ef/', 'consonant'),
        ('G', 'g', '/dʒiː/', 'consonant'),
        ('H', 'h', '/eɪtʃ/', 'consonant'),
        ('I', 'i', '/aɪ/', 'vowel'),
        ('J', 'j', '/dʒeɪ/', 'consonant'),
        ('K', 'k', '/keɪ/', 'consonant'),
        ('L', 'l', '/el/', 'consonant'),
        ('M', 'm', '/em/', 'consonant'),
        ('N', 'n', '/en/', 'consonant'),
        ('O', 'o', '/əʊ/', 'vowel'),
        ('P', 'p', '/piː/', 'consonant'),
        ('Q', 'q', '/kjuː/', 'consonant'),
        ('R', 'r', '/ɑː/', 'consonant'),
        ('S', 's', '/es/', 'consonant'),
        ('T', 't', '/tiː/', 'consonant'),
        ('U', 'u', '/juː/', 'vowel'),
        ('V', 'v', '/viː/', 'consonant'),
        ('W', 'w', '/ˈdʌbəl juː/', 'consonant'),
        ('X', 'x', '/eks/', 'consonant'),
        ('Y', 'y', '/waɪ/', 'vowel'),
        ('Z', 'z', '/zed/', 'consonant'),
    ]

    for i, (upper, lower, name, category) in enumerate(letters, start=1):
        Letter.objects.create(
            uppercase=upper,
            lowercase=lower,
            name=name,
            category=category,
            order=i,
            pronunciation_in_slovak='',  # Add later if needed
        )

def unload_english_alphabet(apps, schema_editor):
    Letter = apps.get_model('alphabet', 'Letter')
    Letter.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('alphabet', '0001_initial'),  # update to your latest migration name
    ]

    operations = [
        migrations.RunPython(load_english_alphabet, reverse_code=unload_english_alphabet),
    ]