# Generated by Django 5.1.1 on 2026-02-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_in_english', models.CharField(max_length=200)),
                ('emoji', models.CharField(max_length=100)),
                ('pronunciation_in_slovak', models.TextField()),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ColourLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour_name', models.CharField(max_length=50)),
                ('colour_hex', models.CharField(blank=True, help_text='e.g., #FF0000', max_length=7, null=True)),
                ('name_in_english', models.CharField(max_length=50)),
                ('pronunciation_in_slovak', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Colour Lesson',
                'verbose_name_plural': 'Colour Lessons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FamilyLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_term', models.CharField(max_length=100)),
                ('vocabulary', models.TextField()),
                ('pronunciation_in_slovak', models.TextField()),
                ('emoji', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Family Lesson',
                'verbose_name_plural': 'Family Lessons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FoodLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vocabulary', models.TextField()),
                ('pronunciation_in_slovak', models.TextField()),
                ('emoji', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NumberLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('name_in_english', models.CharField(max_length=50)),
                ('pronunciation_in_slovak', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Number Lesson',
                'verbose_name_plural': 'Number Lessons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SchoolLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vocabulary', models.TextField()),
                ('pronunciation_in_slovak', models.TextField()),
                ('emoji', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
