# Generated by Django 5.1.1 on 2025-11-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('name_in_english', models.CharField(max_length=20)),
                ('overview', models.TextField()),
                ('vocabulary', models.TextField()),
                ('pronunciation_in_slovak', models.TextField()),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SchoolLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('name_in_english', models.CharField(max_length=20)),
                ('overview', models.TextField()),
                ('vocabulary', models.TextField()),
                ('pronunciation_in_slovak', models.TextField()),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
