# Generated by Django 5.1.1 on 2026-02-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_loadlesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animallesson',
            name='emoji',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='familylesson',
            name='emoji',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='foodlesson',
            name='emoji',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='schoollesson',
            name='emoji',
            field=models.CharField(max_length=10),
        ),
    ]
